In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('my_movies.csv')

In [3]:
data.head()

,V1,V2,V3,V4,V5,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile
0,Sixth Sense,LOTR1,Harry Potter1,Green Mile,LOTR2,1,0,1,1,0,1,0,0,0,1
1,Gladiator,Patriot,Braveheart,NaN,NaN,0,1,0,0,1,0,0,0,1,0
2,LOTR1,LOTR2,NaN,NaN,NaN,0,0,1,0,0,1,0,0,0,0
3,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0
4,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0

In [4]:
data.shape

(10, 15)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   V1             10 non-null     object
 1   V2             10 non-null     object
 2   V3             7 non-null      object
 3   V4             2 non-null      object
 4   V5             1 non-null      object
 5   Sixth Sense    10 non-null     int64
 6   Gladiator      10 non-null     int64
 7   LOTR1          10 non-null     int64
 8   Harry Potter1  10 non-null     int64
 9   Patriot        10 non-null     int64
 10  LOTR2          10 non-null     int64
 11  Harry Potter2  10 non-null     int64
 12  LOTR           10 non-null     int64
 13  Braveheart     10 non-null     int64
 14  Green Mile     10 non-null     int64
dtypes: int64(10), object(5)
memory usage: 1.3+ KB

In [6]:
# we used one hot encoding method for categorical data
data1 = pd.get_dummies(data)

In [7]:
data1

,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile,...,V2_LOTR,V2_LOTR1,V2_LOTR2,V2_Patriot,V3_Braveheart,V3_Gladiator,V3_Harry Potter1,V3_Sixth Sense,V4_Green Mile,V5_LOTR2
0,1,0,1,1,0,1,0,0,0,1,...,0,1,0,0,0,0,1,0,1,1
1,0,1,0,0,1,0,0,0,1,0,...,0,0,0,1,1,0,0,0,0,0
2,0,0,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
5,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
6,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,1,1,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
9,1,1,0,0,0,0,0,1,0,1,...,1,0,0,0,0,1,0,0,1,0

In [8]:
from mlxtend.frequent_patterns import apriori,association_rules

In [9]:
#we take support=0.2 to check that how many associations we got

In [10]:
freq = apriori(data1,min_support=0.2,use_colnames=True)
freq

    support                                           itemsets
0       0.6                                      (Sixth Sense)
1       0.7                                        (Gladiator)
2       0.2                                            (LOTR1)
3       0.2                                    (Harry Potter1)
4       0.6                                          (Patriot)
..      ...                                                ...
76      0.4  (V2_Patriot, Sixth Sense, Patriot, Gladiator, ...
77      0.4  (V2_Patriot, V1_Gladiator, Sixth Sense, Gladia...
78      0.4  (V2_Patriot, V1_Gladiator, Sixth Sense, Patrio...
79      0.4  (V2_Patriot, V1_Gladiator, Patriot, Gladiator,...
80      0.4  (V2_Patriot, V1_Gladiator, Sixth Sense, Patrio...

[81 rows x 2 columns]

In [11]:
#Now we take support=0.5 to check that how many associations we got
freq1 = apriori(data1,min_support=0.5,use_colnames=True)
freq1

    support                                        itemsets
0       0.6                                   (Sixth Sense)
1       0.7                                     (Gladiator)
2       0.6                                       (Patriot)
3       0.6                                  (V1_Gladiator)
4       0.6                                    (V2_Patriot)
5       0.5                        (Sixth Sense, Gladiator)
6       0.6                            (Patriot, Gladiator)
7       0.6                       (V1_Gladiator, Gladiator)
8       0.6                         (V2_Patriot, Gladiator)
9       0.6                         (V1_Gladiator, Patriot)
10      0.6                           (V2_Patriot, Patriot)
11      0.6                      (V1_Gladiator, V2_Patriot)
12      0.6              (V1_Gladiator, Patriot, Gladiator)
13      0.6                (V2_Patriot, Patriot, Gladiator)
14      0.6           (V1_Gladiator, V2_Patriot, Gladiator)
15      0.6             (V1_Gladiator, Patriot, V2_Patriot)
16      0.6  (V1_Gladiator, Patriot, V2_Patriot, Gladiator)

In [12]:
#After analyzing both supports 0.2 and 0.5 we use support 0.5

In [14]:
asso = association_rules(freq1,metric='lift',min_threshold=1)
asso

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Sixth Sense),(Gladiator),0.6,0.7,0.5,0.833333,1.190476,0.08,1.8
1,(Gladiator),(Sixth Sense),0.7,0.6,0.5,0.714286,1.190476,0.08,1.4
2,(Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
3,(Gladiator),(Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
4,(V1_Gladiator),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
5,(Gladiator),(V1_Gladiator),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
6,(V2_Patriot),(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
7,(Gladiator),(V2_Patriot),0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
8,(V1_Gladiator),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
9,(Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
10,(V2_Patriot),(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
11,(Patriot),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
12,(V1_Gladiator),(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
13,(V2_Patriot),(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
14,"(V1_Gladiator, Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
15,"(V1_Gladiator, Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
16,"(Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
17,(V1_Gladiator),"(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
18,(Patriot),"(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
19,(Gladiator),"(V1_Gladiator, Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
20,"(V2_Patriot, Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
21,"(V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
22,"(Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
23,(V2_Patriot),"(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
24,(Patriot),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
25,(Gladiator),"(V2_Patriot, Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
26,"(V1_Gladiator, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
27,"(V1_Gladiator, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
28,"(V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
29,(V1_Gladiator),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
30,(V2_Patriot),"(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
31,(Gladiator),"(V1_Gladiator, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8
32,"(V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
33,"(V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
34,"(V2_Patriot, Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
35,(V1_Gladiator),"(V2_Patriot, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
36,(Patriot),"(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
37,(V2_Patriot),"(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
38,"(V1_Gladiator, Patriot, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.000000,1.428571,0.18,inf
39,"(V1_Gladiator, Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
40,"(V1_Gladiator, V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
41,"(V2_Patriot, Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.000000,1.666667,0.24,inf
42,"(V1_Gladiator, Patriot)","(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
43,"(V1_Gladiator, V2_Patriot)","(Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
44,"(V1_Gladiator, Gladiator)","(V2_Patriot, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
45,"(V2_Patriot, Patriot)","(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
46,"(Patriot, Gladiator)","(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
47,"(V2_Patriot, Gladiator)","(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
48,(V1_Gladiator),"(V2_Patriot, Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
49,(Patriot),"(V1_Gladiator, V2_Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
50,(V2_Patriot),"(V1_Gladiator, Patriot, Gladiator)",0.6,0.6,0.6,1.000000,1.666667,0.24,inf
51,(Gladiator),"(V1_Gladiator, Patriot, V2_Patriot)",0.7,0.6,0.6,0.857143,1.428571,0.18,2.8

In [15]:
asso[asso['lift']>=1.5]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
8,(V1_Gladiator),(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
9,(Patriot),(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
10,(V2_Patriot),(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
11,(Patriot),(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
12,(V1_Gladiator),(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
13,(V2_Patriot),(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
15,"(V1_Gladiator, Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
16,"(Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
17,(V1_Gladiator),"(Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
18,(Patriot),"(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
21,"(V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,"(Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
23,(V2_Patriot),"(Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
24,(Patriot),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
27,"(V1_Gladiator, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
28,"(V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
29,(V1_Gladiator),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
30,(V2_Patriot),"(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
32,"(V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
33,"(V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
34,"(V2_Patriot, Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
35,(V1_Gladiator),"(V2_Patriot, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
36,(Patriot),"(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
37,(V2_Patriot),"(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
39,"(V1_Gladiator, Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
40,"(V1_Gladiator, V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
41,"(V2_Patriot, Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
42,"(V1_Gladiator, Patriot)","(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
43,"(V1_Gladiator, V2_Patriot)","(Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
44,"(V1_Gladiator, Gladiator)","(V2_Patriot, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
45,"(V2_Patriot, Patriot)","(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
46,"(Patriot, Gladiator)","(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
47,"(V2_Patriot, Gladiator)","(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
48,(V1_Gladiator),"(V2_Patriot, Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
49,(Patriot),"(V1_Gladiator, V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
50,(V2_Patriot),"(V1_Gladiator, Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf

In [16]:
asso.sort_values('lift',ascending=False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
21,"(V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
43,"(V1_Gladiator, V2_Patriot)","(Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
23,(V2_Patriot),"(Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
24,(Patriot),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
45,"(V2_Patriot, Patriot)","(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
27,"(V1_Gladiator, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
28,"(V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
29,(V1_Gladiator),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
30,(V2_Patriot),"(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
32,"(V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
33,"(V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
34,"(V2_Patriot, Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
35,(V1_Gladiator),"(V2_Patriot, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
36,(Patriot),"(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
37,(V2_Patriot),"(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
44,"(V1_Gladiator, Gladiator)","(V2_Patriot, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
39,"(V1_Gladiator, Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
40,"(V1_Gladiator, V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
41,"(V2_Patriot, Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,"(Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf

In [18]:
#Now we take confidence as metrics to check the association
asso2 = association_rules(freq,metric='confidence',min_threshold=1)
asso2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Green Mile),(Sixth Sense),0.2,0.6,0.2,1.0,1.666667,0.08,inf
1,(V1_Sixth Sense),(Sixth Sense),0.2,0.6,0.2,1.0,1.666667,0.08,inf
2,(V3_Sixth Sense),(Sixth Sense),0.4,0.6,0.4,1.0,1.666667,0.16,inf
3,(V4_Green Mile),(Sixth Sense),0.2,0.6,0.2,1.0,1.666667,0.08,inf
4,(Patriot),(Gladiator),0.6,0.7,0.6,1.0,1.428571,0.18,inf
...,...,...,...,...,...,...,...,...,...
394,"(Sixth Sense, Patriot)","(V2_Patriot, V3_Sixth Sense, V1_Gladiator, Gla...",0.4,0.4,0.4,1.0,2.500000,0.24,inf
395,"(V3_Sixth Sense, Sixth Sense)","(V2_Patriot, V1_Gladiator, Patriot, Gladiator)",0.4,0.6,0.4,1.0,1.666667,0.16,inf
396,"(V3_Sixth Sense, Patriot)","(V2_Patriot, Sixth Sense, V1_Gladiator, Gladia...",0.4,0.4,0.4,1.0,2.500000,0.24,inf
397,"(V3_Sixth Sense, Gladiator)","(V2_Patriot, Sixth Sense, V1_Gladiator, Patriot)",0.4,0.4,0.4,1.0,2.500000,0.24,inf
398,(V3_Sixth Sense),"(V2_Patriot, V1_Gladiator, Sixth Sense, Patrio...",0.4,0.4,0.4,1.0,2.500000,0.24,inf

In [19]:
asso.sort_values('confidence',ascending=False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
26,"(V1_Gladiator, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.0,1.428571,0.18,inf
32,"(V1_Gladiator, Patriot)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
24,(Patriot),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
46,"(Patriot, Gladiator)","(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
45,"(V2_Patriot, Patriot)","(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
27,"(V1_Gladiator, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
28,"(V2_Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
29,(V1_Gladiator),"(V2_Patriot, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
30,(V2_Patriot),"(V1_Gladiator, Gladiator)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
44,"(V1_Gladiator, Gladiator)","(V2_Patriot, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
33,"(V1_Gladiator, V2_Patriot)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
22,"(Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
34,"(V2_Patriot, Patriot)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf
35,(V1_Gladiator),"(V2_Patriot, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
36,(Patriot),"(V1_Gladiator, V2_Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
37,(V2_Patriot),"(V1_Gladiator, Patriot)",0.6,0.6,0.6,1.0,1.666667,0.24,inf
38,"(V1_Gladiator, Patriot, V2_Patriot)",(Gladiator),0.6,0.7,0.6,1.0,1.428571,0.18,inf
39,"(V1_Gladiator, Patriot, Gladiator)",(V2_Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
40,"(V1_Gladiator, V2_Patriot, Gladiator)",(Patriot),0.6,0.6,0.6,1.0,1.666667,0.24,inf
41,"(V2_Patriot, Patriot, Gladiator)",(V1_Gladiator),0.6,0.6,0.6,1.0,1.666667,0.24,inf